//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eventino.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT
    {
        public ACCOUNT()
        {
            this.COMMENTs = new HashSet<COMMENT>();
            this.LIKEs = new HashSet<LIKE>();
            this.REPLies = new HashSet<REPLY>();
            this.VIEWs = new HashSet<VIEW>();
        }
    
        public int ACCOUNTID { get; set; }
        public Nullable<int> LOGINID { get; set; }
        public Nullable<int> COUNTRYID { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public string GENDER { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string PHONENUMBER { get; set; }
        public string MARITALSTATUS { get; set; }
        public string IMAGE { get; set; }
        public string CoverImage { get; set; }
    
        public virtual COUNTRY COUNTRY { get; set; }
        public virtual LOGIN LOGIN { get; set; }
        public virtual ICollection<COMMENT> COMMENTs { get; set; }
        public virtual ICollection<LIKE> LIKEs { get; set; }
        public virtual ICollection<REPLY> REPLies { get; set; }
        public virtual ICollection<VIEW> VIEWs { get; set; }
    }
}
