//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eventino.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENTTYPE
    {
        public EVENTTYPE()
        {
            this.EVENTs = new HashSet<EVENT>();
        }
    
        public int EVENTTYPEID { get; set; }
        public string EVENTTYENAME { get; set; }
    
        public virtual ICollection<EVENT> EVENTs { get; set; }
    }
}
