//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eventino.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPLY
    {
        public int REPLYID { get; set; }
        public Nullable<int> ACCOUNTID { get; set; }
        public Nullable<int> COMMENTID { get; set; }
        public string REPLY1 { get; set; }
        public Nullable<int> LOGINID { get; set; }
        public string CREATEDATE { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual COMMENT COMMENT { get; set; }
        public virtual LOGIN LOGIN { get; set; }
    }
}
